### ISSUE TITLE
Does pulsar have --dry-run option?

### ISSUE THREAD

**Issue by zx1986** [nebulab/pulsar#58]
like `cap local deploy --dry-run --trace`

**Comment by mtylty** [comment]
@zx1986 with pulsar's latest version you can pass pretty much whatever you want to capistrano by using the `task` command.

The command you're talking about should be something like:

```
pulsar task your_application production "deploy --dry-run --trace"
```

The `"` are needed because cap args need to be passed as the last argument.

If that works for you I think we can close this 😄

**Comment by zx1986** [comment]
It works perfect! you are awesome! thanks!
